name: flutter_touch_spin
description: Simple number input spinner Widget for Flutter. Inspired by Bootstrap Touchspin
version: 2.0.0
homepage: https://github.com/danvick/flutter_touch_spin

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
